const {authenticate} = require('../middlewares/authenticate.middleware')
let userController = require('../controllers/user.controller')

module.exports = (app) => {
    app.route('/user')
        .post(authenticate, userController.createUser)
    app.route('/user/email')
        .get(authenticate, userController.findByEmail)
    app.route('/user/verify-account')
        .post(userController.verifyAccount)
    app.route('/user/forgot-password')
        .post(userController.forgotPassword)
    app.route('/user/reset-password')
        .post(userController.resetPassword)
    app.route('/user/:id')
        .get(authenticate, userController.findById)
        .delete(authenticate, userController.deleteUser)
        .patch(authenticate,userController.updateUser)
    app.route('/users')
        .get(authenticate, userController.findAllUsers)
    app.route('/user-by-applications')
        .post(authenticate, userController.findApplicationUsers)
    app.route('/get_auth_user')
        .get(authenticate, userController.getAuthUser)
}
