#api-gateway-test-integration:
#  variables:
#    NODE_ENV: test
#    X_AUTH_TOKEN: wbdhAC6uTVn873E2MrU8a
#  stage: test
#  image: node:lts-alpine
#  services:
#    - postgres
#  before_script:
#    - cd user-service
#  script:
#    - npm install --quiet
#    - npm run test
#  environment:
#    name: Production
#  only:
#     changes:
#     - api-gateway/**/*

api-gateway-build:
    stage: build
    image: docker:latest
    services:
      - docker:dind
    before_script:
          - apk update
          - apk add --update nodejs npm
          - cd api-gateway
          - cat $API_GATEWAY_SERVICE_ENV > .env
          - docker login -u "$GITLAB_REGISTRY_USERNAME" -p "$GITLAB_REGISTRY_PASSWORD" $CI_REGISTRY
    script:
        - npm install --quiet
        - npm run build
        - docker build --tag $CI_REGISTRY/pa-esgi/backend_microservices/api-gateway .
        - docker tag $CI_REGISTRY/pa-esgi/backend_microservices/api-gateway $CI_REGISTRY/pa-esgi/backend_microservices/api-gateway:latest
        - docker push $CI_REGISTRY/pa-esgi/backend_microservices/api-gateway:latest
    environment:
        name: Production
    only:
        changes:
        - api-gateway/**/*

api-gateway-deploy:
  stage: deploy
  image: lwolf/helm-kubectl-docker:latest
  environment:
    name: Production
  before_script:
    - mkdir ~/.kube/
    - echo $KUBECONFIG_OVH | base64 -d > config
    - mv config ~/.kube/
    - kubectl get namespace
    - ls -all
  script:
    - helm upgrade --set service.apiGateway.image=$CI_REGISTRY/pa-esgi/backend_microservices/api-gateway:latest --install --values=deploy/api-gateway/values.yaml api-gateway deploy/api-gateway
  only:
    changes:
      - api-gateway/**/*
